name: flashcardsmobile
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  sqflite: ^2.2.0+3
  path_provider: ^2.0.11
  flutter_staggered_grid_view: 0.4.0
  flip_card: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  fonts:
  - family: Sans
    fonts:
      - asset: assets/fonts/ProductSans-Regular.ttf
      - asset: assets/fonts/ProductSans-Italic.ttf
        style: italic
      - asset: assets/fonts/ProductSans-Bold.ttf
        weight: 700

